acc/urls.py
from django.urls import path
from . import views

app_name = "acc"  # 별칭을 app 마다 분리
urlpatterns = [
    path('index/' ,views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('update/', views.update, name="update"),
    path('chpass/', views.chpass, name="chpass"),
    path('delete/', views.delete, name="delete"),
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/' , views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
    path('creply/<bpk>', views.creply, name="creply")
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"
urlpatterns = [
    path('index/' , views.index, name="index"),
    path('create/', views.create, name="create")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include("board.urls")),
    path('trans/', include("trans.urls")),
    path('tts/', include("tts.urls")),
    path('vote/', include("vote.urls")),
    path('book/', include("book.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    pubdate = models.DateTimeField()
    likey = models.ManyToManyField(User, blank=True, related_name="likey")

    def __str__(self):
        return f"{self.writer} 의 {self.subject}"

class Reply(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f"{self.board} 에 {self.replyer} 가 남긴 댓글"

board/views.py
from django.shortcuts import redirect, render
from .models import Board, Reply
from django.utils import timezone
from django.core.paginator import Paginator
# Create your views here.

def creply(request, bpk):
    b = Board.objects.get(id=bpk)
    c = request.POST.get("com")
    Reply(board=b, replyer=request.user, comment=c).save()
    return redirect("board:detail", bpk)

def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if request.user == r.replyer:
        r.delete()
    else:
        pass # 20일차 메세지
    return redirect("board:detail", bpk)



def index(request):
    pg = request.GET.get("page", 1)
    cate = request.GET.get("cate", "")
    kw = request.GET.get("kw", "")

    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
        else:
            b = Board.objects.none()
    else:
        b = Board.objects.all()

    b = b.order_by("-pubdate")
    
    pag = Paginator(b, 2)
    obj = pag.get_page(pg)

    context = {
        "bset" : obj,
        "kw" : kw,
        "cate" : cate
    }
    return render(request, "board/index.html", context)



def update(request, bpk):
    b = Board.objects.get(id=bpk)

    if b.writer != request.user:
        # 20 일차 경고!!
        return redirect("board:index")

    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject, b.content = s,c
        b.save()
        return redirect("board:detail", bpk)

    context = {
        "b" : b
    }
    return render(request, "board/update.html", context)

def create(request) :
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        t = timezone.now()
        Board(subject=s, writer=request.user, content=c, pubdate=t).save()
        return redirect("board:index")
    return render(request, "board/create.html")


def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if request.user == b.writer:
        b.delete()
    else:
        pass # 20 일차! 협박하자!
    return redirect("board:index")

def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    context = {
        "b": b,
        "rset":r
    }
    return render(request, "board/detail.html", context)

templates/board/create.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>게시글 작성</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label"><b>SUBJECT</b></label>
            <input type="text" name="sub" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>WRITER</b></label>
            <input type="text" class="form-control" value="{{ user }}" disabled>
        </div>
        <div class="mb-3">
            <label class="form-label"><b>CONTENT</b></label>
            <textarea class="form-control" name="con" style="height: 150px;"></textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">생성</button>
        </div>
    </form>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>{{ b.subject }}</b></h1>

    <div class="row mt-5">
        <div class="col-sm-9">
            <textarea class="form-control" style="height:200px" disabled>{{ b.content }}</textarea>
        </div>
        <div class="col-sm-3">
            <img src="{{ b.writer.getpic }}" width="100%">
            <div class="text-center mt-3">
                <h5>written by <b>{{ b.writer }}</b></h5>
            </div>
            <div class="text-end mt-2">
                {{ b.pubdate|date:'Y년 n월 j일, H:i' }}
            </div>
        </div>
    </div>

    <div class="text-end mt-4">
        <a href="{% url 'board:index' %}" class="btn btn-dark">글목록</a>

        {% if user == b.writer %}
            <a href="{% url 'board:update' b.id %}" class="btn btn-dark">글수정</a>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#remove">
                글삭제
            </button>
        {% endif %}
    </div>

    <div class="mt-3 mb-4 text-end">
        <button type="button" class="btn btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#star">
            🍺
        </button>
    </div>

    <hr>

    <form method="post" action="{% url 'board:creply' b.id %}">
        {% csrf_token %}
        <div class="row mt-3 mb-5">
            <div class="col-sm-10">
                <input type="text" name="com" class="form-control" placeholder="댓글을 입력해주세요..">
            </div>
            <div class="col-sm-2">
                <button class="btn btn-dark" style="width: 100%;">댓글작성</button>
            </div>
        </div>
    </form>


    {% if rset %}
        {% for i in rset %}

            <div class="row mt-5">
                <div class="col-sm-3 text-center">
                    <img src="{{ i.replyer.getpic }}" width="80%">
                    <div class="mt-3">
                        <h5><b>{{ i.replyer }}</b></h5>
                    </div>
                </div>
                <div class="col-sm-9">
                    <textarea class="form-control" style="height: 120px;" disabled>{{ i.comment }}</textarea>
                    <div class="text-end mt-3">
                        {% if user == i.replyer %}
                            <a href="{% url 'board:dreply' b.id i.id %}" class="btn btn-danger btn-sm">댓글삭제</a>
                        {% endif %}
                    </div>
                </div>
            </div>

        {% endfor %}
    {% else %}

    {% endif %}



    <!-- Modal -->
    <div class="modal fade" id="remove" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>게시글 삭제 알림창</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    '{{b.subject}}' 글을 정말 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                    <a href="{% url 'board:delete' b.id %}" class="btn btn-danger">삭제</a>
                </div>
            </div>
        </div>
    </div>

    <form method="post" action="{% url 'book:create' %}">
        {% csrf_token %}
        <div class="modal fade" id="star" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">북마크 추가 알림창</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body text-center">
                        <div class="text-end mb-4">
                            <input name="impo" type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off">
                            <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br>
                        </div>
                        <textarea class="form-control" name="scon" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
                        <input type="hidden" name="sname" value="[BOARD]::{{b.subject}}">
                        <input type="hidden" name="surl" value="{{ request.path }}">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-warning">추가</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}

    {% load mathfilters %}
    <h1><b>게시판</b></h1>
        
    <div class="text-end">
        <a href="{% url 'board:create' %}" class="btn btn-dark">게시글생성</a>
    </div>

    <table class="table table-hover mt-4">
        <thead>
            <tr class="table-dark">
                <th scope="col">NO</th>
                <th scope="col">SUBJECT</th>
                <th scope="col">SUMMARY</th>
                <th scope="col">WRITER</th>
                <th scope="col">LIKEY</th>
            </tr>
        </thead>
        <tbody>
            {% if bset %}
                {% for i in bset %}
                    <tr>
                        <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                        <td><a class="sub" href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                        <td>{{ i.content|truncatewords:10 }}</td>
                        <td>{{ i.writer }}</td>
                        <td>0</td>
                    </tr>
                {% endfor %}
            {% else %}
                {% if kw %}
                    <tr>
                        <th colspan="5">검색결과가 없습니다.. 😒</th>
                    </tr>
                {% else %}
                    <tr>
                        <th colspan="5">첫번째 게시글을 작성해주세요! 👏</th>
                    </tr>
                {% endif %}
            {% endif %}
        </tbody>
    </table>


    <form>
        <div class="row mt-3 mb-5">   
            <div class="col-sm-2">
                <select name="cate" class="form-select form-select-sm">
                    <option value="sub" {% if cate == "sub" %} selected {% endif %}>제목</option>
                    <option value="wri" {% if cate == "wri" %} selected {% endif %}>작성자</option>
                    <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option>
                </select>
            </div>
            <div class="col-sm-8">
                <input type="text" name="kw" value="{{kw}}" class="form-control form-control-sm">
            </div>
            <div class="col-sm-2">
                <button class="btn btn-dark btn-sm" style="width:48%">검색</button>
                <a class="btn btn-dark btn-sm" href="{% url 'board:index' %}" style="width:48%">리셋</a>
            </div>
        </div>
    </form>



    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if bset.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page=1&cate={{cate}}&kw={{kw}}">처음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.previous_page_number }}&cate={{cate}}&kw={{kw}}">이전</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">처음</a></li>
                <li class="page-item disabled"><a class="page-link">이전</a></li>
            {% endif %}

            {% for i in bset.paginator.page_range %}
                {% if i >= bset.number|sub:4 and bset.number|add:5 >= i %}
                    <li class="page-item {% if bset.number == i %} active {% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a></li>
                {% endif %}
            {% endfor %}

            {% if bset.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.next_page_number }}&cate={{cate}}&kw={{kw}}">다음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}&cate={{cate}}&kw={{kw}}">마지막</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">다음</a></li>
                <li class="page-item disabled"><a class="page-link">마지막</a></li>
            {% endif %}
        </ul>
    </nav>



    <style>
        .sub {
            text-decoration: none;
            color:black;
            font-weight: bold;
        }
        .sub:hover{
            color:red;
        }
    </style>

{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>게시글수정</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label"><b>SUBJECT</b></label>
            <input type="text" name="sub" value="{{b.subject}}" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>WRITER</b></label>
            <input type="text" class="form-control" disabled value="{{ b.writer }}">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>CONTENT</b></label>
            <textarea class="form-control" name="con" style="height: 150px;">{{ b.content }}</textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">수정</button>
        </div> 
    </form>

{% endblock %}